name: Release Binary

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install MinGW & CMake
        run: sudo apt-get update && sudo apt-get install -y mingw-w64 cmake

      - name: Build Project
        run: bash scripts/build

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/release/Otherworld-Legends.dll
            build/release/injector.exe
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
